{
 "title": "Sleeve Eval",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{namespace=~'sleeve-system|cass-operator'}[10s])) by (le, controller))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "workqueue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "workqueue_depth{namespace=~\"cass-operator|sleeve-system\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{container=\"manager\", namespace=\"cass-operator\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controller Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "controller client operation frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(controller_client_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "controller client operation latency AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "# Calculate average client operation latency per operation type over the last minute\nsum by (operation) (\n    rate(controller_client_request_duration_seconds_sum[1m])\n)\n/\nsum by (operation) (\n    rate(controller_client_request_duration_seconds_count[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconcile rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "    sum(rate(controller_runtime_reconcile_total{namespace=\"cass-operator\", controller=\"cassandradatacenter_controller\"}[1m]))",
     "legendFormat": "all"
    },
    {
     "expr": "    sum(rate(controller_runtime_reconcile_total{namespace=\"cass-operator\", controller=\"cassandradatacenter_controller\", result=\"error\"\n    }[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "    sum(rate(controller_runtime_reconcile_total{namespace=\"cass-operator\", controller=\"cassandradatacenter_controller\", result!=\"error\"\n    }[1m]))",
     "legendFormat": "success/requeue"
    }
   ]
  },
  {
   "title": "controller client operation latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(controller_client_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "go_goroutines{service=\"cass-operator-controller-manager-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconcile invocation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, controller) (rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"cassandradatacenter_controller\", namespace=\"cass-operator\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, controller) (rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"cassandradatacenter_controller\", namespace=\"cass-operator\"}[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, controller) (rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"cassandradatacenter_controller\", namespace=\"cass-operator\"}[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "  sum(rate(controller_runtime_reconcile_time_seconds_sum{\n             controller=\"cassandradatacenter_controller\"\n         }[1m]))\n         /\n         sum(rate(controller_runtime_reconcile_time_seconds_count{\n            controller=\"cassandradatacenter_controller\"\n         }[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Cluster / API metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "web hook latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "# Replace <your_webhook_name> with the name defined in your ValidatingWebhookConfiguration\nhistogram_quantile(0.99, sum by (le, name) (rate(apiserver_admission_webhook_admission_duration_seconds_bucket{type=\"validating\", name=\"vcassandradatacenter.kb.io\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Replace <your_webhook_name> with the name defined in your ValidatingWebhookConfiguration\nhistogram_quantile(0.99, sum by (le, name) (rate(apiserver_admission_webhook_admission_duration_seconds_bucket{type=\"validating\", name=\"sleeve-webhook.discrete.events\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Replace <your_webhook_name> with the name defined in your ValidatingWebhookConfiguration\nhistogram_quantile(0.99, sum by (le, name) (rate(apiserver_admission_webhook_admission_duration_seconds_bucket{type=\"admit\", name=\"simple-kubernetes-webhook.acme.com\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# pods in tracey namespaace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"tracey\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cassandradatacenter API request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=\"cassandradatacenters\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(apiserver_request_total{resource=\"cassandradatacenters\", verb=~\"DELETE|POST\"}[1m]))",
     "legendFormat": "client workload ops"
    }
   ]
  },
  {
   "title": "cassandracontroller active workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{namespace=~\"cass-operator|sleeve-sytem\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "node CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "        100 * (\n      1 - avg by (instance) (\n        rate(node_cpu_seconds_total{\n            mode=\"idle\",\n            job=\"node-exporter\",\n            instance=\"172.20.0.2:9100\"\n        }[1m])\n      )\n    )",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_cpu_usage_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container memory working set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"manager\", namespace=\"cass-operator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster-wide network traffic (Mb/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "# Total cluster receive rate in Megabytes per second (MB/s)\nsum(rate(node_network_receive_bytes_total{job=\"node-exporter\", device!=\"lo\"}[1m])) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}